apiVersion: 1

datasources:
  - id: 1
    orgId: 1
    name: "InfluxDB"
    type: "influxdb"
    typeLogoUrl: "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
    database: "mydb"
    access: "direct"
    url: "http://localhost:8086"
    password: ""
    user: ""
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
