{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4}}
spec:
  selector:
    {{- include "bifrost.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: p2p
      port: {{ .Values.service.ports.p2p }}
      targetPort: {{ .Values.ports.p2p }}
    - protocol: TCP
      name: rpc
      port: {{ .Values.service.ports.rpc }}
      targetPort: {{ .Values.ports.rpc }}
{{- end }}
