version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file:
    - provisioning/grafana/env
    ports:
      - 3000:3000
    volumes:
      - ./provisioning/grafana:/etc/grafana/provisioning
    
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: always
    ports:
      - 9411:9411

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    env_file:
    - provisioning/influxdb/env
    ports:
      - 8086:8086
    # volumes:
    #    - ./data/influxdb:/var/lib/influxdb

  # visualMailbox:
  #   image: ouven/akka-visual-mailbox-visualization
  #   ports:
  #     - 8080:8080
  #     - 60009:60009/udp
    