# # Default values for bifrost.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

name: bifrost-node

image:
  name: ghcr.io/topl/bifrost-node
  tag: latest

replicas: 1

resources:
  limits:
    cpu: 2.0
    memory: 4000Mi
  requests:
    cpu: 100m
    memory: 128Mi

podSecurityContext:
  runAsUser: 1001 # TODO: Update Bifrost Docker container to use high UID. Add CKV_K8S_40 as a check.
  runAsGroup: 0
  fsGroup: 0
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

args: # Refer to CLI: https://github.com/Topl/Bifrost#command-line-reference
# args: ['--seed', 'test', '--forge']
# args: ['--network', 'valhalla']

command:
# command: ["tail", "-f", "/dev/null"] # Use this to debug Bifrost and exec into the running pod.

service:
  enabled: true
  type: ClusterIP
  ports:
    p2p: 9084
    rpc: 9085

ports:
  p2p: 9084
  rpc: 9085

volume:
  mountDirectory: /opt/docker/.bifrost
  # GKE specific storage classes: standard, standard-rwo, premium-rwo
  storageClass: default
  storageSize: 10Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 30
  periodSeconds: 60 # Perform check every x seconds.

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 30
  periodSeconds: 60 # Perform check every x seconds.
