name: Generate Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 1.8
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 8
        graalvm-version: 19.3.1
        native-image: false
 
#     - name: Show java version
#       run: java -version
      
#     - name: Run tests
#       run: sbt test
      
    - name: Generate documentation
      run: sbt doc

    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./target/scala-2.12/api
        cname: bifrost.docs.topl.co
